# Generated by Django 4.2.7 on 2026-03-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='snapshots/')),
                ('dominant_emotion', models.CharField(blank=True, max_length=30)),
                ('emotions_data', models.JSONField(default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('transcribed_text', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('keywords_matched', models.JSONField(default=list)),
                ('ai_feedback', models.TextField(blank=True)),
                ('improvement_suggestions', models.TextField(blank=True)),
                ('face_emotions', models.JSONField(default=dict)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(default='python', max_length=30)),
                ('difficulty', models.CharField(default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('total_questions', models.IntegerField(default=5)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('feedback_summary', models.TextField(blank=True)),
                ('improvement_tips', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('readiness', models.CharField(blank=True, max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('dsa', 'Data Structures & Algorithms'), ('system_design', 'System Design'), ('behavioral', 'Behavioral'), ('javascript', 'JavaScript'), ('database', 'Database / SQL'), ('devops', 'DevOps'), ('ml', 'Machine Learning')], max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('question_text', models.TextField()),
                ('expected_keywords', models.JSONField(default=list)),
                ('ideal_answer_outline', models.TextField(blank=True)),
                ('time_limit_seconds', models.IntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
